### ISSUE TITLE
maker最基础的设置不显示，能否像popup一样有插槽方便插入htmlElement？

### ISSUE THREAD

**Issue by nauYieM** [timeroute/mapvue#14]
代码：
`<script setup>
import { ref, reactive } from "vue";
import { accessToken } from "../../utils/mapUtil";

const state = reactive({
  center: [120, 30],
  visible: true,
  scale: 1,
  text: "Hi",
});
</script>

<template>
  <div class="container">
    <v-map
      :accessToken="accessToken"
      :options="{
        center: state.center,
        zoom: 4,
      }"
    >
      <v-marker :center="state.center" />
      <v-popup
        v-model:visible="state.visible"
        :center="state.center"
        :options="{
          anchor: 'bottom',
          offset: [0, -36],
          closeOnClick: false,
          closeOnMove: false,
        }"
      >
        {{ state.text }}
      </v-popup>
    </v-map>
  </div>
</template>

<style scoped>
.container {
  height: 100vh;
  width: 100%;
}
</style>`

版本：
"mapvue": "^0.3.3",
"mapbox-gl": "^3.5.2",
"vue": "^3.2.13",

**Comment by nauYieM** [comment]
仔细检查了一下代码，是main.js中对于警告的设置影响了
// app.config.warnHandler=(warnHandlerMsg)=>{
// }
注释掉就没事了

**Comment by timeroute** [comment]
参考文档的例子，是支持的
