### ISSUE TITLE
binding map properties

### ISSUE THREAD

**Issue by edanweis** [timeroute/mapvue#9]
Is there any way to control map parameters like zoom, bearing, pitch etc. by changing props? something like `:mapStyle.sync="mapStyle"`?

Or store the map object for watching properties? eg: 
```
onMapLoaded(event) {
      // in component
      this.map = event.map;
```

**Comment by timeroute** [comment]
all the parameters of mapboxgl.Map instance are in `options` of `<v-map>`, you can see from [update props](https://mapvue.netlify.app/components/vmap.html#update-props).

there are two ways to take the map object

1. <v-map> component expose the `map` object, you can ref the component to get it

```
<script setup>
const mapRef = ref()

const handleLoaded = () => {
  console.log(mapRef.value.map)
}
</script>
<template>
  <v-map ref="mapRef" @loaded="handleLoaded" />
</template>
```

2. mapvue store the map object by provide/inject, you can inject it in custom component under <v-map> component.

A component
```
<template>
  <v-map>
    <B />
  </v-map>
</template>
```

B component
``` B component
<script setup>
import { mapvueSymbol } from 'mapvue'
const map = inject(mapvueSymbol)
</script>
<template>
</template>
```

**Comment by timeroute** [comment]
According to you question, I update the doc to explain how to get map instance in mapvue, visit [get map instance](https://mapvue.netlify.app/guide/get-map-instance.html)

**Comment by edanweis** [comment]
@timeroute thank you!
